### ISSUE TITLE
Remove patch for Omnibox URL formatting

### ISSUE THREAD

**Issue by wchen342** [ungoogled-software/ungoogled-chromium#1051]
In wchen342/ungoogled-chromium-android/issues/21 someone mentioned that in vanilla `chromium`, if `#enable-mark-http-as` is enabled then the protocal part (`https://`) will be hidden, while only `http://` will be shown as a warning. Supposedly it will be better this way and the reasoning is in the mentioned issue.

However in `ungoogled-chromium` there is a patch (I believe it is `disable-formatting-in-omnibox.patch`) explicitly disables that behavior. @Eloston I wonder why the patch is included in the first place? Is there a conclusion on which way is actually better?

**Comment by Madis0** [comment]
One thing to note is that upstream Chromium  (desktop only) will get a context menu option for toggling the elision too, so the patch could be removed either way. https://bugs.chromium.org/p/chromium/issues/detail?id=1061576

**Comment by Eloston** [comment]
> I wonder why the patch is included in the first place?

I made that patch years ago, possibly even before I created the ungoogled-chromium project. Things were more naive and experimental back then.

Considering that Google is adding an option to show the full URL (thanks @Madis0 for linking the crbug), I see no reason to keep this patch. However, since this patch has been in ungoogled-chromium for so long, I think we should keep it until Google's changes land in stable Chromium (which will be Chromium 84?) since it's the only way to show the full URL right now.

**Comment by Eloston** [comment]
Update: According to https://bugs.chromium.org/p/chromium/issues/detail?id=1061576#c29, it seems like we'd need a patch to always enable the context menu option because of field trial testing. So it's probably easier to hold onto `disable-formatting-in-omnibox.patch` until Chromium permanently enables the feature.

**Comment by PF4Public** [comment]
What is the current state of this issue?
