### ISSUE TITLE
Push notifications not working?

### ISSUE THREAD

**Issue by usermyname12** [ungoogled-software/ungoogled-chromium#1482]
Twitch and reddit examples but i am sure it doesn't work anywhere else. I have them enabled from windows settings, browser settings and the accounts from the websites but still nothing popups. Only way to work is by this https://www.bennish.net/web-notifications.html and only when i have the tab open. Is it a bug of a feature?

**Comment by 3c0** [comment]
I don't know if I should open a new bug report, but the web push notifications also work erratically for me on macOS Mojave (10.14.6) with Chromium Version 95.0.4638.69 (Official Build, ungoogled-chromium) (x86_64).

Last time I tried, https://www.bennish.net/web-notifications.html was not working at all. Today, it is working as expected. Delayed notifications appear even when on another window.

But when I try to enable notifications on some other sites like https://keepa.com/ for example, it makes Chromium crash! To reproduce:

1. Create an account on https://keepa.com/
2. Go to your account Settings / Notifications
3. Click on "Web Push Notifications" toggle button ![keepa com_](https://user-images.githubusercontent.com/7715141/139828264-47c8cf60-a8a4-45e4-a61a-a4f42001fb7b.png)
4. If notifications for keepa.com are not already authorised on Chomium, a popup will appear, so click on Authorise
5. Immediate crash!

Maybe the bug is not directly related to the Chromium notification system and comes from the **Push API** or the **Service Workers API**?

See #1503

**Comment by 3c0** [comment]
Still crashing on keepa.com: macOS Chromium Version 96.0.4664.110 (Official Build, ungoogled-chromium) (x86_64)

**Comment by 3c0** [comment]
Still crashing on keepa.com: macOS Chromium Version 97.0.4692.71 (Official Build, ungoogled-chromium) (x86_64)

**Comment by PF4Public** [comment]
Is this still an issue?

**Comment by SteveOverSea** [comment]
Push notifications don't work for me. Tested via https://cleverpush.com/en/test-notifications/.

Using the Push API the Promise from `registration.pushManager.subscribe()` never resolves or rejects.
I already adjusted notification settings in macOS settings and tested with Chrome (Version 120.0.6099.129 (Official Build) (arm64)) - in Chrome it worked fine.

Version 120.0.6099.109 (Official Build, ungoogled-chromium) (arm64).
MacOS 14.1.2

**Comment by realies** [comment]
Not working here either.
Version 126.0.6478.114 (Official Build, ungoogled-chromium) (arm64)
macOS 15.0 Beta (24A5279h)

**Comment by realies** [comment]
@networkException, can this be reopened please?

**Comment by networkException** [comment]
Notifications probably use Firebase Cloud Messaging which we do not allow the browser to connect to for obvious reasons. This is expected.

**Comment by realies** [comment]
@networkException, it can potentially be implemented via something else: https://github.com/ungoogled-software/ungoogled-chromium/discussions/1900#discussioncomment-8821259
