### ISSUE TITLE
update 134

### ISSUE THREAD

**Issue by DAIIIIIIIIIIIIII** [ungoogled-software/ungoogled-chromium#2019]
charlouncher just updated me to the last version of ungoogled chromium just released and immediately the brwser broke. gives me error in all tabs, even on the settings, all extensions crash instantly and I can not search for anything

**Comment by networkException** [comment]
You mean https://github.com/henrypp/chrlauncher?

**Comment by DAIIIIIIIIIIIIII** [comment]
> You mean https://github.com/henrypp/chrlauncher?

yes

**Comment by networkException** [comment]
According to the readme that is using builds from https://github.com/macchrome/winchrome, however I cannot see 103.0.5060.134-1 listed.

Also note that those builds are considered third party

**Comment by AGlezB** [comment]
Same here. Nothing works after updating to 103.0.5060.134

**Comment by PF4Public** [comment]
We do not provide support for third-party binaries.
Freshly built 134 works without issues (commenting right from it).

**Comment by networkException** [comment]
> we probably wouldn't have these problems if you created a browser installation executable (for windows) that also updates; why don't you develop one?

Because automatic updates raise various serious concerns about governance (who decides which binaries get used and has the ability to push out updates), infrastructure (where are the binaries stored and how does the browser get notified about an update) and privacy (should the browser contact a server on its own to check for updates).

Nobody has dealt with those issues yet and I don't think anyone will anytime soon. We are not a company that can simply assert authority over all those.

We do however offer regularly updated binaries produced by openly accessible build scripts run on GitHub-hosted action runners with public logs: https://github.com/ungoogled-software/ungoogled-chromium-windows

**Comment by B-eT-a** [comment]
quote:

> my solution was to delete the bin folder, so it downloaded the package again, now everything is fine.

worked wonderfully here.... all good now :)

**Comment by AGlezB** [comment]
> quote:
> 
> > my solution was to delete the bin folder, so it downloaded the package again, now everything is fine.
> 
> worked wonderfully here.... all good now :)

It seems someone rolled back the update to `.134`. Now chrlauncher downloads version `.114` instead.

![image](https://user-images.githubusercontent.com/12277525/180081105-9e5afaba-c9cc-4c64-b150-8c2bd5f2c32e.png)
