### ISSUE TITLE
ctrl+alt+p results in error message since 104, unable to type apostrophe

### ISSUE THREAD

**Issue by kangarko** [ungoogled-software/ungoogled-chromium#2052]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 104.0.5112.81 (Official Build, ungoogled-chromium) (64-bit)

### Tested upstream?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there

### Description

Previously, pressing ctrl+alt+p printed the ' character, now it gives an error message: https://i.imgur.com/ys2k7NW.png

### How to Reproduce?

1. Set Slovak keyboard layout (QWERTZ)
2. Type ctrl+alt+p

### Actual behaviour

Error message: https://i.imgur.com/ys2k7NW.png, I am unable to type apostrophe unless I open another window which is frustrating and annoying

### Expected behaviour

Either let me type apostrophe or please give us a flag to disable this annoying error message

### Additional context

I understand this may be a normal feature unfortunately it breaks Slovak keyboard in the sense that it makes typing ' impossible from Chromium. Please add a flag to disable it.

I tried using available shortcut extensions for Chrome without success (i.e. the error did still open and the letter was not inserted into input field)

**Comment by tomasz1986** [comment]
This isn't specific to Ungoogled Chromium, is it? I assume the regular Chromium has the same problem, right? If yes, then it's probably yet another unfortunate example of English-only developers having no consideration for other language input methods.

Personally, I'd love to have a built-in way to customise the normally hard-coded shortcuts (like the Ctrl+P for print, Ctrl+T for new tab, etc.). This would probably become a much larger feature request though 🙃.

**Comment by PF4Public** [comment]
> 5 minutes

Sorry, but that's waaay too optimistic :(

**Comment by kangarko** [comment]
> > 5 minutes
> 
> Sorry, but that's waaay too optimistic :(

I said I apology if I am mistaken :D I had no idea. Maybe I can donate some to get rid of this annoyance? Literally typing a reply here takes time to copy the damn stupid apostrophe haha

**Comment by tomasz1986** [comment]
I've done some testing with the Slovak keyboard layout installed.

The problem seems to be about the following.

1. Normally, AltGr+P is supposed to input `'`. Alternatively, pressing both LCtrl and LAlt is supposed to emulate AltGr (e.g. on laptop keyboards without AltGr), which is why LCtrl+LAlt+P can also be used to input `'`.
2. The above is supposed to work OS-wide, and other/most applications seem to respect it.
3. Chromium however overrides the shortcut with its own:
   - LCtrl+P triggers the browser print dialog.
   - LCtrl+LAlt+P triggers the OS print dialog.
4. Because of this, the LCtrl+LAlt doesn't act as AltGr anymore, hence you cannot input `'`.

I assume you've got no AltGr (right Alt) key on your keyboard, have you?

Honestly, I wouldn't count for a quick fix to this one. As a workaround, I would suggest using a program like AutoHotkey to override the browser's keyboard shortcut and force it to input `'` instead of the showing the print dialog. I can prepare a very simple AutoHotkey script for you to do this, if you're interested of course.

Solving this with an extension doesn't seem viable either, as it only seems possible to assign either LCtrl or LAlt to a custom shortcut, but not both at the same time.

**Comment by PF4Public** [comment]
Would it be possible to just apply a patch over the sources to disable those shortcuts and rebuild the browser locally? If ever @kangarko considers rebuilding it from sources of-course.

**Comment by kangarko** [comment]
@tomasz1986 I appreciate your help! I actually found two solutions:

1) Creating Norwegian QWERTY keyboard in Windows 11 and simply using shortcut Win+spacebar to shift between these two keyboards when using Chrome. Since Norwegian keyboard does not use a shortcut, it is straighforward to type the apostrophe. Not ideal but it's pretty fast.

2) Thanks to your question about my alt keys I found that by pressing the right alt key it still works :) Only the left alt key is overiden by Chrome

Thanks so much, amazing community, amazing work on Ungoogled, I do appreciate your help!
