### ISSUE TITLE
Can't import user data from google chrome

### ISSUE THREAD

**Issue by ezxpro** [ungoogled-software/ungoogled-chromium#2117]
### Description

On 1st launch, I can import data from several browsers, except google chrome.

### Who's implementing?

- [ ] I'm willing to implement this feature myself

### The problem

I think this is a feature that's in chromium, implying it was removed from ungoogled chromium. It's actually not a great idea though. If the intent is to free you from google services, it complicates matters when you can't bring your data from chrome. I have a very large amount of data in chrome and the only downside of ungoogled chromium for me is that I can't import it.

### Possible solutions

Enable importing data from chrome.

**Comment by networkException** [comment]
I haven't seen any such import dialog in chromium or ungoogled-chromium but that might be platform dependent. As chrome and chromium both use the same user data format I don't think chromium would have any handling of importing chrome data whatsoever.

It should be sufficient to simply copy the chrome user data directory to the location chromium stores user data

**Comment by ezxpro** [comment]
@networkException 
I tried this, Chromium crashes immediately after launching it

**Comment by ezxpro** [comment]
@tomasz1986 yeah, I tried deleting most folders from the user profile, I was able to retain bookmarks, extensions and history, but it complained the settings were corrupt and reset them, it also deleted the cookies.

If possible, I'd like to keep the cookies, because I'm logged to a lot of websites on chrome. Passwords aren't important because I use a password manager

**Comment by PF4Public** [comment]
Please provide more information on the issue, so that someone could help you further.

**Comment by ezxpro** [comment]
> Please provide more information on the issue, so that someone could help you further.

I can't imagine how I can provide further information on this issue.

Basically, when you first launch this browser, it offers to import user data from other browsers through a wizard, and Google Chrome is not one of them.
That's basically it, I don't know what else I could say.

**Comment by PF4Public** [comment]
> Basically, when you first launch this browser, it offers to import user data from other browsers through a wizard, and Google Chrome is not one of them.

Because it makes no sense importing from Google Chrome as they are the same <s>picture</s> browser essentially.

**Comment by tomasz1986** [comment]
I actually think this makes the most sense, e.g. when the user wants to get rid of the closed source Chrome and switch to Ungoogled Chromium (or even just Chromium). However, as already described earlier in https://github.com/ungoogled-software/ungoogled-chromium/issues/2117#issuecomment-1279973518, this kind of a switch between different Chrome/Chromium variants isn't something that Google has probably ever considered, so there is no code that is responsible for that. I would guess that this type of data import would probably have to be written from scratch.

However, some of the data mentioned here are literally single files. Instead of trying to copy and re-use the whole Chrome user data folder, how about trying to copy only the single files, e.g.

```
Default/Bookmarks
Default/History
Default/Login Data
Default/Login Data For Account
Default/Network/Cookies
```

This is for the `Default` profile. If you've got other profiles, then look for the same files inside `Profile <number>` folders. When it comes to Extensions, the files and configuration are scattered throughout multiple folders, e.g. `Extensions`, `Local Extension Settings`, `Managed Extension Settings`, `Sync Extension Settings`, multiple folders starting with `chrome-extension_` inside `IndexedDB`, and I believe some extension settings are also stored in `Local Storage`.

I would suggest to try replacing these files one by one (with the exception for extensions) with the browser closed, then start it and see whether the "imported" data works.

**Comment by ezxpro** [comment]
@PF4Public I think @tomasz1986 has given a good enough answer.
So, apparently there is no default option to import data from Google Chrome. Knowing which files should be imported from the Data Folder should be enough.

**Comment by TorutheRedFox** [comment]
it doesn't carry over extensions though

**Comment by weirdal3333** [comment]
I'd like to bump this and have it reopened! This feature is extremely important for gaining more users!

**Comment by ari-party** [comment]
Bumping in the big 25

**Comment by ilcane87** [comment]
Adding my +1, starting today Chrome is enforcing the deactivation of mv2 extensions, without allowing manually re-enabling them anymore.
There are still workarounds for now, but they're intended to stop working by the end of the year, so I expect a lot of Chrome users will be looking for a replacement that offers the most similar experience with a painless transition.

**Comment by distante** [comment]
Brave has an option to import everything from Chrome. Maybe there can we check how it is done.

**Comment by ezxpro** [comment]
apparently, no one seems to care.  It's been more than 3 years since I reported this and the problem is still there. No way to import data from Google Chrome into this browser.
