### ISSUE TITLE
lost all settings after setting default browser

### ISSUE THREAD

**Issue by ceeeeeeeeeeeeeeeeb** [ungoogled-software/ungoogled-chromium#2136]
I set it as my default browser in  chrome://settings/defaultBrowser ,  but  when I open a url link in Word ，a new ungoogled chromium browser seems to be opened , in which all settings are reset  and all extensions  are lost .
and , by  enter  chrome://version/   in the new browser  ,  the info says, user data files  path is C:\Users\admin\AppData\Local\Chromium\User Data\Default  .  obviously  it says this new browser is'nt portable . 

and by opening ungoogled-chromium-portable.exe   ,   all extensions are there and  chrome://version/  page says it  exactly is portable   because user data files path is ./data/default  .
and the new browser seems from ./app/chrome.exe   

why these two .exe  produce different  configuration？
is there any way to set the ungoogled-chromium-portable.exe  as default browser rather than ./app/chrome.exe  ?

similar problem also occurs in brave-portable.exe.

so ,how can I solve this? 
This problem has confused me a fews days,  by contrast , the [Cent Browser portable edition ](https://www.centbrowser.cn/history.html)

, in which only exists one .exe,  and does not have this problem.

**Comment by tomasz1986** [comment]
This is because portable versions aren't designed to be set as default (of any software really, unless separately implemented by the said application). You can still do it, but doing so will require manual fiddling with the registry.

You can find the necessary information in the Internet, e.g. https://superuser.com/questions/51264/how-do-i-add-new-applications-to-the-set-default-programs-list-in-windows-vist has at least a few answers where the specific registry entries are listed. Of course, you will need to adjust them to your browser name and paths.

Also, where does "ungoogled-chromium-portable.exe" come from specifically? There is no official release of Ungoogled Chromium like that.

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
> 
thanks a lot !
sorry , I find I came to the wrong place...   and the portable version (ungoogled-chromium-portable.exe) comes from [here](https://portapps.io/app/ungoogled-chromium-portable/) . I should have gone there to post this issue, sorry..

**Comment by PF4Public** [comment]
Looks like there's nothing left to do regarding this issue — closing.
