### ISSUE TITLE
Google account sign-in

### ISSUE THREAD

**Issue by figurativly1984** [ungoogled-software/ungoogled-chromium#2315]
I can see that the setting used to exist but now when I go into settings, I do not see an option to disable the option "Allow Chromium sign-in". I want to stay signed in on Gmail but not on Chromium. If anyone knows if there is another setting or a flag to disable this, that would be greatly appreciated.

**Comment by PF4Public** [comment]
This setting was a no-op and was removed from the UI.

**Comment by figurativly1984** [comment]
sorry but what does no-op mean 😅

**Comment by PF4Public** [comment]
No operation. It didn't do anything.

**Comment by figurativly1984** [comment]
ah ok so no way to disable it then right?

**Comment by PF4Public** [comment]
No way to enable, I'd say ;)

**Comment by figurativly1984** [comment]
It seems to be enabled by default though? If i sign into gmail and then search something through google, on the right hand corner, all of my google accounts appear. Is this simply unavoidable because I'm using the google search engine?

**Comment by PF4Public** [comment]
You're mixing separate things. 

Chromium login is for logging into Google via browser in order to use Google synchronization services within browser (tabs, passwords and whatnot). All of that does not function in ungoogled-chromium by design, therefore the setting you mentioned was removed.

Logging into Gmail will inevitably have you logged into Google on all of its services since Google <s>out of meanness</s> cleverly uses the same domain over all the services.

**Comment by figurativly1984** [comment]
I see. Thanks for helping :)
