### ISSUE TITLE
Ungoogled Chromium doesn't try to install ExtensionInstallForceList

### ISSUE THREAD

**Issue by hollowshiroyuki** [ungoogled-software/ungoogled-chromium#2523]
### OS/Platform

Arch Linux

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

Version 117.0.5938.88 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [ ] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

Ungoogled Chromium doesn't install the extensions from the managed policy ExtensionInstallForceList

### How to Reproduce?

1. Install the following managed policy
```json
{
  "ExtensionInstallForcelist": [
    "cjpalhdlnbpafiamejdnhcphjbkeiagm;http://clients2.google.com/service/update2/crx?response=updatecheck&x=id%3Dcjpalhdlnbpafiamejdnhcphjbkeiagm"
  ]
}
```
- For Ungoogled Chromium on Archlinux `/etc/chromium/policies/managed/policy.json`
- For Google Chrome on Archlinux `/etc/opt/chrome/policies/managed/policy.json` (to compare)

2. Start UG/Chrome with an empty profile.

### Actual behaviour

Ungoogled Chromium won't show any extension in about://extensions and searching the `chrome_debug.log` for the extension id or `Forced extension` (in case of failure) won't return anything.

### Expected behaviour

Google Chrome actually shows a policy managed extension
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/35398794/caa0a7eb-1134-4a2b-a918-5c1284aace49)
And searching in the `chrome_debug.log` for the extension id returns multiple lines.

### Relevant log output

```sh
// Sample case of failure for Chromium Web Store
[153207:153207:0924/012949.495575:WARNING:load_error_reporter.cc(74)] Extension error: Expected version "1.5.3", but version was "1.5.3.1"
[153207:153207:0924/012949.495619:WARNING:force_installed_metrics.cc(481)] Failed to install 1 forced extensions.
[153207:153207:0924/012949.495637:WARNING:force_installed_metrics.cc(518)] Forced extension ocaahdebbfolfmndjeplogmgcagdmblk failed to install with data=failure_reason: 20; install_error_detail: 4; install_stage: 4; downloading_cache_status: 2

// Sample case of success for uBlock Origin
[153207:153247:0924/012948.403527:VERBOSE1:content_verifier.cc(630)] OnFetchComplete cjpalhdlnbpafiamejdnhcphjbkeiagm success:1
[153364:1:0924/012948.513346:VERBOSE1:script_context.cc(143)] Created context:
  extension id:           cjpalhdlnbpafiamejdnhcphjbkeiagm
  frame:                  0x3aaf001edda0
  URL:                    
  context_type:           BLESSED_EXTENSION
  effective extension id: cjpalhdlnbpafiamejdnhcphjbkeiagm
  effective context type: BLESSED_EXTENSION
```

### Additional context

Relevant documentation :
- https://chromeenterprise.google/policies/#ExtensionInstallForcelist
- https://serverfault.com/a/354635

For extensions in the Chrome Extension Store, the update URL part is optional, I added the explicit manifest URL because I figured Ungoogled Chromium domains nullification would cause issues.

**Comment by hollowshiroyuki** [comment]
@PF4Public Ungoogled Chromium supports other enterprise policies, here are the ones I'm using :
```
{
	"ShowHomeButton": true,
	"SavingBrowserHistoryDisabled": true,
	"DefaultBrowserSettingEnabled": false,
	"AutofillCreditCardEnabled": false,
	"PaymentMethodQueryEnabled": false,
	"DefaultSearchProviderEnabled": true,
	"DefaultSearchProviderSearchURL": "https://start.duckduckgo.com/?q={searchTerms}"
}
```
So I believe it should support `ExtensionInstallForceList` as well ?

My personal use case is a bit weird. I tend to just nuke my `~/.config/chromium` every once in a while, as I don't really care about whatever it might contain. But I'd like to have some extensions always preinstalled when restarting after clearing it, like uBlock or Chromium Web Store.

In large deployments this feature could be really useful to deploy ablocker, password manager or enterprise related extensions to users.

For standard users it could make it easier for them to manage their chromium config in their dotfiles and would allow them to have "mandatory" extensions always installed even in new profiles.

**Comment by hollowshiroyuki** [comment]
I didn't have the time yesterday to also test in classic Chromium, I just tried now and it seems to work.
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/35398794/48a65005-2a90-40e3-b9c9-b888ac7e9dcc)

**Comment by PF4Public** [comment]
> So I believe it should support `ExtensionInstallForceList` as well ?

But installing extensions in ungoogled-chromium does not work by default. If you nuke your profile, you cannot install extensions by default. Have you tried manually installing extension, removing it and attempting to install it via policy?

**Comment by hollowshiroyuki** [comment]
> installing extensions in ungoogled-chromium does not work by default

Because it needs to be enabled by the `extension-mime-request-handling@2` feature flag ?

I also have a sample `Local State` file copied in `.chromium/` every time I wipe the chromium directory to re-enable wayland support and to reenable installing with crx files.
```json
{
  "browser": {
    "enabled_labs_experiments": [
      "enable-webrtc-pipewire-capturer@1",
      "extension-mime-request-handling@2",
      "ozone-platform-hint@1"
    ]
  }
}
```
When starting Ungoogled Chromium with a fresh `.chromium/` it will overwrite the file to add all the other values but it will keep the flags already in it.

It seems Ungoogled Chromium supports a similar way to install extensions with the External Extension Descriptor but you already need to have the crx files locally.
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#installing-the-crx-file

Does Ungoogled Chromium has a policy to not initiate any download or request by itself ?

**Comment by PF4Public** [comment]
@hollowshiroyuki I have a feeling that because of all Google domains being substituted it would be impossible for a browser to download any crx in background. And because of that one should use mime handling to manually (after a confirmation popup) initiate extension installation. In this case the download itself was initiated by the user and therefore excluded from domain substitution.

If my analysis is correct, there is no way you could use this policy unless you build a custom version that excludes domain substitution on code-path needed for automatic extension installation.

**Comment by hollowshiroyuki** [comment]
I see :thinking: 
I still think it's weird, the domain substitution would break this feature even if there shouldn't be the need for a Google domain anywhere in the process when the update manifest is provided along with the extension id ?

**Comment by PF4Public** [comment]
> when the update manifest is provided along with the extension id ?

One could browse through sources in order to find out how this policy actually works. Good starting point might be [?q=ExtensionInstallForceList](https://source.chromium.org/search?q=ExtensionInstallForceList&sq=)

**Comment by Pandapip1** [comment]
Can this be reopened? I've bumped into the same issue.

**Comment by PF4Public** [comment]
@Pandapip1 Do you have a solution for this?

**Comment by Pandapip1** [comment]
I do not have a solution for this. I'm using normal googled chromium for the time being.

**Comment by PF4Public** [comment]
@Pandapip1 This issue was closed as it needs more investigation and more details. Given that no one is interested in investigating further there is not much value in reopening it anyway.

**Comment by PF4Public** [comment]
> How would you recommend I go about debugging this?

Find out how it is supposed to work (regardless of ungoogled-chromim) to begin with. https://github.com/ungoogled-software/ungoogled-chromium/issues/2523#issuecomment-1735952523

**Comment by powellnorma** [comment]
@PF4Public I think re-opening the issues shows others that there is something where work can be done (better discoverability). A closed issue to me signals "done". Just because there wasn't yet someone who has had the time, doesn't mean there isn't interest in this feature. What do you think?

**Comment by PF4Public** [comment]
> What do you think?

I think the label "need info" says it all.

> Just because there wasn't yet someone who has had the time, doesn't mean there isn't interest in this feature.

I think it means exactly that: no one is interested.

> shows others that there is something where work can be done (better discoverability)

I think that better discoverability makes no difference without anyone interested in fixing bugs.

> A closed issue to me signals "done".

I beg your pardon, but it signals "Not planned", which is not "done" in my opinion.

**Comment by powellnorma** [comment]
> I think that better discoverability makes no difference without anyone interested in fixing bugs.

No, but maybe there is someone interested in "fixing things", so he/she looks for open issues, and looks for something interesting to them. That's a normal workflow, I think. Other projects have a label "help wanted", which gives even better discoverability. I think it would be appropriate here, since you even gave hints on where one could start looking. It could be a great issue for people (potential new maintainers) looking to engage with this project, I think. But if is closed, such people might not find it (the likelihood decreases, I think, significantly). Do you see my point?

**Comment by PF4Public** [comment]
> Do you see my point?

Absolutely. My answers might"ve been too simplistic, but I have my reasons. You see, every now and then comes someone with idealistic ideas, so it might get tiresome explaining same things again and again.

But if you insist, lets try once more.

> there is someone interested in "fixing things"

Someone interested in fixing things should be capable of finding things to fix.

But anyway, what if I tell you I've almost never seen anyone coming to this project and fixing things. Given that I would assume such a person does not exist, which would invalidate your point here. Yes, there are people, who actually come to fix things, but those never have troubles identifying issues, so I would also assume that current state of things works fine.

> so he/she looks for open issues, and looks for something interesting to them. That's a normal workflow, I think.

Yes, there are plenty of open issues ready to be worked on. But on the other hand it makes no sense keeping incomplete issues open, because the are, well incomplete. Because they are somehow obscure and do not attract any interest whatsoever. One might say they do no harm, but the opposite is true. We are automating tedious things, so we have some Workflows running in background. With lots of open issues we sometimes hit secondary limits of GitHub. You never notice that because you receive no notifications about that. I do however.

> Other projects have a label "help wanted", which gives even better discoverability.

[We are no different.](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+state%3Aopen+label%3A%22help+wanted%22)

> I think it would be appropriate here, since you even gave hints on where one could start looking.

You might be onto something here, I've actually planned doing a housekeeping of sorts, defining labels and so on, but I'm occupied a lot offline at the moment. So it has to wait.
