### ISSUE TITLE
Add option to use old UI. Chrome UI 2024 is bad.

### ISSUE THREAD

**Issue by Rexadev** [ungoogled-software/ungoogled-chromium#2742]
#### Description
add a flag to use Old UI.

## Google keeps just adding
1. unnecessary clicks,
2. banners
3. unnatural behavior
4. remove features and buttons
 
# 1. 'Quick Bookmark' Behavior
window changing folder for current page's bookmark doesn't change until saved but clicking outside saves it and other...
Regression since v119 #   'quick bookmark' window changing folder for current page's bookmark doesn't change until saved but clicking outside saves it and other...

![video](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/d671ca38-c548-469b-a238-c11a6619b949)
![video](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/cef5ddd3-26dc-4383-b65f-2caa98ebb9c7)

# 2. All Bookmarks and Other Bookmarks 2 Names for 1 Folder
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/9597ac9e-ecc9-4361-b6e8-1df6078d819f)  ![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/894402a7-067a-45b4-95ab-76626835ead2)
 
# 3. Old bookmark 'Edit Bookmark' with Quick access to Folder hierarchy view.

1. chrome://flags/#simplified-bookmark-save-flow removed 
2. disable #power-bookmarks-side-pane removed this flag in v119 so you need to enable #temporary-unexpire-flags-m118
3. extension alternative https://github.com/a90120411/BookmarkPlus
4. Disscussion on Chromium https://issues.chromium.org/issues/41496433

![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/f3ba9585-468b-4dd1-8ebe-061816417276)

# 4. 3rd party cookie Panel with no option to select cookies
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/93453e70-c2fb-44b1-a59e-bf1d9dfc45da)
 
# 5. "Bookmark added" Banner
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/62152714/0378a220-a2e9-4e8b-81e7-6e02eab6d323)
 
# 6. Too much space in toolbar (disable #chrome-refresh-2023 #chrome-webui-refresh-2023 fixes it)
# 7. Too much space between tabs (disable #chrome-refresh-2023 #chrome-webui-refresh-2023 fixes it)

### Additional context

**Comment by PF4Public** [comment]
Have you attempted to disable the new UI?

**Comment by networkException** [comment]
For the record, unless upstream provides a way to disable UI changes we are very unlikely to forward port anything given the high effort.

**Comment by Rexadev** [comment]
> Have you attempted to disable the new UI?

If you mean #chrome-refresh-2023 #chrome-webui-refresh-2023 I have disabled both and still 2024 UI problems exists.

except 

6. Too much space in toolbar
7. Too much space between tabs

**Comment by Rexadev** [comment]
@networkException Would it possible to bring chrome://flags/#simplified-bookmark-save-flow

**Comment by Rexadev** [comment]
@macchrome

**Comment by networkException** [comment]
I don't understand

**Comment by onlineinternet** [comment]
You can already revert to the old UI.
Go to chrome://flags
Disable "Chrome Refresh 2023"
Disable everything with "steady state"
Disable "Customize Chrome Side Panel" and "Customize Chrome Side Panel Extension Card"

**Comment by Rexadev** [comment]
I tried those and these are not fixed -
3. Old bookmark 'Edit Bookmark' with Quick access to Folder hierarchy view.
4.  3rd party cookie Panel with no option to select cookies
5. "Bookmark added" Banner
2. All Bookmarks and Other Bookmarks 2 Names for 1 Folder
1. 'Quick Bookmark' Behavior

Only thses are fixed
6. Too much space in toolbar (disable #chrome-refresh-2023 #chrome-webui-refresh-2023 fixes it)
7. Too much space between tabs (disable #chrome-refresh-2023 #chrome-webui-refresh-2023 fixes it)

@onlineinternet

**Comment by PF4Public** [comment]
> I tried those and these are not fixed - 3. Old bookmark 'Edit Bookmark' with Quick access to Folder hierarchy view. 4. 3rd party cookie Panel with no option to select cookies 5. "Bookmark added" Banner 2. All Bookmarks and Other Bookmarks 2 Names for 1 Folder
> 
> 1. 'Quick Bookmark' Behavior

Have you attempted fixing them yourself? Would you be willing to submit a PR?

**Comment by kcollins7** [comment]
Google seems intent on pushing this UI refresh on everyone and M124 is likely the last version where the flags to disable the new UI refresh are going to be available. I'm actively looking for a new browser that doesn't have their awful new design philosophy so it would be greatly appreciated if the flags to disable the old UI are maintained.

**Comment by 1t0many** [comment]
With every major version of Chromium, the flags mentioned that disable the new UI become progressively more difficult to set. Recently, the flag was _hidden_ from `chrome://flags`, requiring command-line switches to set it, but with Chrome 126, something&hellip; else is blocking the flags from working.

Not putting in an effort to keep the classic UI available would mean forcing the new UI on Ungoogled Chromium users in the same way as Google is doing to Chrome users, which in my opinion is pretty much the opposite of what Ungoogled Chromium is all about.

**Comment by networkException** [comment]
> Not putting in an effort to keep the classic UI available would mean forcing the new UI on Ungoogled Chromium users in the same way as Google is doing to Chrome users, which in my opinion is pretty much the opposite of what Ungoogled Chromium is all about.

no, ungoogled-chromium is not about maintaining UI that will be removed anyways.

> ungoogled-chromium retains the default Chromium experience as closely as possible

**Comment by 1t0many** [comment]
> ungoogled-chromium retains the default Chromium experience as closely as possible

That would apply more if it was necessary to manually _re-create_ the old UI in order to have it. But if I understand Google's changes correctly, that is not the case here: the old UI is not _gone_ &#x2014; only the flags to disable the new UI are gone.

To illustrate my point, here is another example. It has been taught to me several times that Windows 11's UI is not completely built from the ground up. Windows 11 is, in fact, just Windows 10 with a bunch of new skins, textures, visual changes, and features added to it. It's like refurbishing a building: the rooms got repainted, perhaps there are some nice decorations added, but it's still the same building underneath the paint.

The new Chromium UI appears to be a similar case. From what I can gather, the new UI does not appear to be part of the current structure &#x2014; rather, it is being _plastered over_ the current UI. This is evident by the fact that disabling the `#customize-chrome-side-panel` flag (while it still existed) causes us to see the old UI: it is like peeling back the new paint to expose the old design that lies underneath.

Looking at ungoogled-chromium's objectives, there is also a goal that reads:

> ungoogled-chromium features tweaks to enhance privacy, control, and transparency.

Google's choice to hide and/or remove the flags that disable this "plastered" UI highly reflects a suppression of control. If they actually _demolish_ the old UI and make the new UI self-sufficient, that is a different story. But as it stands, it appears that the new UI is almost completely based off the old UI, and Google is trying to put as many locks on the old UI as possible.

This is not a request to save the old UI for millions of years to come so that we can apply it on Chromium 291 a hundred years later. This is a request to remove the locks on the old UI that suppress our control, for as long as the old UI still exists.

**Comment by PF4Public** [comment]
> The idea here is not to preserve the old UI even after it gets removed — the goal is to remove the locks on the old UI that suppress our control, for as long as the old UI still exists.

Are you up to the task?

**Comment by 1t0many** [comment]
@PF4Public What do you mean? I'm an ungoogled-chromium user, not a developer.

**Comment by PF4Public** [comment]
@1t0many You see, idea is a good thing, but without implementation it's worth nothing :(

**Comment by 1t0many** [comment]
@PF4Public Yeah, I understand. I was actually somewhat surprised that no one has tried to do this already, considering that there are a _lot_ of people out there who hate the new UI, many of which are power users, of which many yet I'm sure have turned to ungoogled-chromium, including myself.

Hopefully my little essay has done its part to show support for this issue and present some justification for why it should be implemented &#x2014; it's the most I could do. While I'd be happy to try implementing it myself if I could, unfortunately I'm not in a position to do so.

**Comment by apprehensions** [comment]
Is it not as easy as reverting a set of git commits that removes the option? Or is it easier said than done?

**Comment by PF4Public** [comment]
@apprehensions @1t0many Even if it might've been as easy as reverting several commits in the past, Chromium codebase constantly receives lots of changes which may change code around those commits, which would make their removal a non-trivial feat as time goes by.

**Comment by mort666** [comment]
Big someone that actually gets physically sick because of the excessive use of rounded corners, this interests me significantly as the braindead move in UI design to this doesn't seem to end, and is increasingly difficult to find workarounds for something that makes it impossible to use a infected UI, I literally stopped using macOS because I couldn't spend more than an hour before getting sick after Apple's infestation of this UI trait..  

So as someone who could put some time into this issue but I have limited time (I have a startup to run), I'd like to look at pulling together said code for this but I have zero history with the Chromium code base as a result it would take way too long to start from zero to work this out. So in order to look into this (for my own sanity) I would appreciate some insight into where in the code base this awfulness is implemented or which commits (as rightly pointed out there are a lot) would be the best place to start looking at to see if it is possible.

**Comment by highbaser** [comment]
@networkException Shame on you.

**Comment by QAQDE** [comment]
They are being inconsistent. On the one hand, they support for enabling the chrome extension manifest v2, which the offical Chrome have already dropped supported. On the other hand, they claim they follow the upstream version.
