### ISSUE TITLE
Get verified on Flathub ?

### ISSUE THREAD

**Issue by erlefloch** [ungoogled-software/ungoogled-chromium#2778]
### Description

Get the flatpak version verified on Flathub, as it's already an official mean of distribution stated in the readme section "Automated or maintained builds".

### Who's implementing?

the authors

### The problem

On Flathub there is now a flag "Unverified" on the [ungoogled-chromium page](https://flathub.org/apps/com.github.Eloston.UngoogledChromium) which suggests that the flatpak is unofficial. 
However it seems to actually be an official mean of distribution stated in the readme section "[Automated or maintained builds](https://github.com/ungoogled-software/ungoogled-chromium#automated-or-maintained-builds)".
![image](https://github.com/ungoogled-software/ungoogled-chromium/assets/90708860/4a8c9b8a-943e-43c5-a0fc-f075217cf1d1)

### Possible solutions

Follow the indications on https://docs.flathub.org/docs/for-app-authors/verification

**Comment by rany2** [comment]
Unfortunately this Flatpak was made before the ungoogled-software organization was created.

**Comment by rany2** [comment]
We're working on it here: https://github.com/flathub/flathub/pull/5098

It's blocked right now because I'm waiting for this to be merged: https://github.com/refi64/cobalt/pull/7

**Comment by Sunspark-007** [comment]
Might be a good idea to post on the main github page that the flatpak has changed owners because in the discover store the update just keeps failing.. the other ungoogled-chromium exists with a manual search and it's possible to install both at the same time, but the app menu can only launch the original.. I will fix my local end, but other people might be running into the same issue.

**Comment by networkException** [comment]
whats "main github page"?

**Comment by Sunspark-007** [comment]
The README.md file on https://github.com/ungoogled-software/ungoogled-chromium

**Comment by networkException** [comment]
I don't know what else to put there besides "Flatpak: Available [in the Flathub repo](https://flathub.org/apps/details/io.github.ungoogled_software.ungoogled_chromium) as io.github.ungoogled_software.ungoogled_chromium"

**Comment by Sunspark-007** [comment]
Just write that people need to uninstall the old version of ungoogled-chromium, make note of any settings or extensions they want to keep, and then start from scratch with the new one.

**Comment by rany2** [comment]
This can be closed now.

**Comment by rany2** [comment]
> Just write that people need to uninstall the old version of ungoogled-chromium, make note of any settings or extensions they want to keep, and then start from scratch with the new one.

False, just run `flatpak update` and say "YES" to the EOL prompt.

https://github.com/flathub/com.github.Eloston.UngoogledChromium/?tab=readme-ov-file#urgent-please-read-this

**Comment by Sunspark-007** [comment]
That's good information, but I didn't see that on the Eloston page and I didn't open the terminal.. I was just wondering why the discover store kept saying there was an update available. When I ran warehouse, I did see the notification that it was EOL which in turn was also a surprise because it seemed so sudden. The EOL notice in warehouse doesn't say to go read, it just says that it's EOL.

**Comment by rany2** [comment]
@Sunspark-007 There is a bug with KDE Discover: https://bugs.kde.org/show_bug.cgi?id=485886
