### ISSUE TITLE
Tab icon is misaligned

### ISSUE THREAD

**Issue by BOY0038v2** [ungoogled-software/ungoogled-chromium#2829]
### OS/Platform

Windows

### Installed

https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### Version

124.0.6367.60

### Have you tested that this is not an upstream issue or an issue with your configuration?

- [ ] I have tried reproducing this issue in Chrome and it could not be reproduced there
- [X] I have tried reproducing this issue in vanilla Chromium and it could not be reproduced there
- [ ] I have tried reproducing this issue in ungoogled-chromium with a new and empty profile using `--user-data-dir` command line argument and it could not be reproduced there

### Description

the Tab icon is misaligned

### How to Reproduce?

Just open a tab

### Actual behaviour

![Screenshot (171)](https://github.com/ungoogled-software/ungoogled-chromium/assets/75845425/668f6e0c-b289-482f-a8be-020f301bd8f7)

### Expected behaviour

icon should be aligned with the Tab Title

**Comment by rmdhnreza** [comment]
This is an upstream issue [https://issues.chromium.org/issues/332081796](https://issues.chromium.org/issues/332081796) and should be fixed in 124.0.6367.80

---
Basically, just reset all about `redesign` settings in `chromium://flags` or command-line. This issue only impacted users who had an opt-out of the Chromium redesign pushed last fall.

**Comment by BOY0038v2** [comment]
Bug fixed on version 124.0.6367.91
I will close the issue. Thanks.
