### ISSUE TITLE
Support Windows 7

### ISSUE THREAD

**Issue by top-master** [ungoogled-software/ungoogled-chromium#2845]
### Description

Support Windows 7

### The problem

Chrome removed Windows 7 support, while many systems run faster with Windows 7.

### Possible solutions

Support Windows 7

**Comment by PF4Public** [comment]
Duplicate of #2507
Please [search existing and closed issues](https://github.com/ungoogled-software/ungoogled-chromium/issues?q=is%3Aissue+windows+7+) for similar ones first

**Comment by networkException** [comment]
This is not happening, not with or because some other project (that) has support.

Also, performance is not a reason to run highly vulnerable software. There are alternatives, especially for anyone with enough technical skills to evaluate their need of running ungoogled-chromium.

I, and by extend this project, will not ship software that compromises user security and including support for platforms that are itself or make the software vulnerable is part of that.

**Comment by networkException** [comment]
Support is not happening, making this a discussion has no value.
