### ISSUE TITLE
Add Google Search to list of installed search engines

### ISSUE THREAD

**Issue by jeffmcneill** [ungoogled-software/ungoogled-chromium#2993]
### Description

Add Google Search to list of installed search engines

### Who's implementing?

- [X] I'm willing to implement this feature myself

### The problem

When selecting a search engine, Google is not present. This requires googling, copying, and pasting codes to manually create the rather popular search engine as a default option. See: https://github.com/ungoogled-software/ungoogled-chromium/discussions/1488

### Possible solutions

Add the Google search engine so that it is available as a choice from a list, rather than requiring the user to enter it manually.

**Comment by PF4Public** [comment]
But the project is literally called "ungoogled"…

**Comment by jeffmcneill** [comment]
"a foolish consistency is the hobgoblin of little minds" -Emerson



> But the project is literally called "ungoogled"…

For Google services ... Nothing prevents someone from using a search engine of choice. This feature request, which I am offering to implement will make the software better for some set of users, without degrading the software for others. 

"A foolish consistency is the hobgoblin of little minds." -- Emerson

**Comment by jeffmcneill** [comment]
Easy to fix: 

https://github.com/ungoogled-software/ungoogled-chromium/blob/master/patches/core/ungoogled-chromium/replace-google-search-engine-with-nosearch.patch

**Comment by PF4Public** [comment]
> Nothing prevents someone from using a search engine of choice.

Nothing prevents someone from using a search engine of choice at the current state. What is the problem again? One could add any search engine and it would be preserved in the profile, no need to do it more than once.

**Comment by jeffmcneill** [comment]
Why remove an option and require someone to add it back manually? The problem is one of usability and convenience.

**Comment by PF4Public** [comment]
> The problem is one of usability and convenience.

Exactly! You nailed it! You cannot have both convenience and privacy at the same time, so everyone has to make their own informed decision and act accordingly. And unfortunately we cannot provide a one-size-fits-all solution.

**Comment by jeffmcneill** [comment]
How does having the search engine configuration present affect security?

**Comment by PF4Public** [comment]
> How does having the search engine configuration present affect security?

I didn't even mention security in my message :) Security — not really, privacy — I bet it does. In this particular case with google search engine at least.

> adding inconvenience

There is no standardised measure of inconvenience, so it is a very subjective thing.

**Comment by rany2** [comment]
Really there is no reason to remove Google search from the default list of search engines, especially given that we already 
have terrible (for privacy anyway) options in that list.

IMO the best path forward is to either:

- remove all other search engines from the list to be impartial,
- or add back Google to the search engine list

Personally I'm in favor of the latter. It's really not straightforward to add Google to the list as a user because it seems that Google omits that OpenSearch XML for Chromium so it doesn't add itself to the list automatically. You might argue that "Ungoogled" Chromium has to be fully ungoogled, but I think that in this case it's fair to have an exception to that rule.

Not having it in the list inconveniences users but keeping it wouldn't do any harm so long as it's not the default. Why should Bing be on the list but not Google? It's not like it will phone home by keeping it as an option.

**Comment by PF4Public** [comment]
> I think that in this case it's fair to have an exception to that rule.

The question would be then, whether it is a good thing to have google search engine to be available so easily for end-users. Yeah, now that I've written it, it looks funny :)

**Comment by rany2** [comment]
I'd say it's a good thing from a harm reduction POV. Even though they're using Google search in UGC, it's still better than having them use Google in vanilla Chromium or Chrome. Making it harder wouldn't necessarily change anyone's mind, they'd probably be frustrated with themselves and uninstall.
