### ISSUE TITLE
I love ungoogled-chromium

### ISSUE THREAD

**Issue by CardealRusso** [ungoogled-software/ungoogled-chromium#399]
Damn, i love this. I can't use a computer without this web browser.

**Comment by Eloston** [comment]
Thanks! Glad you're liking it.

**Comment by macandchief** [comment]
Same here!

Great project, fantastic work, well done.

**Comment by tonowoe** [comment]
Same! Especially the pre-built packages are SUPER helpful. I love how they get updated fast for debian.

**Comment by Eloston** [comment]
@Obsessive Huh, that's not something your hear everyday. Out of curiosity, what made you switch?

**Comment by UnnoTed** [comment]
I wrote a extension to make it easier to install extensions from the webstore by following the url method stated in the [faq](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-from-the-chrome-webstore), All that it does is get chrome's version and extension's id and insert it into the crx url, The #extension-mime-request-handling flag is still required.
https://github.com/UnnoTed/Ungoogled-Chromium-Extension-Installer

**Comment by scottttttt** [comment]
I love it too, thanks so much!

**Comment by anchev** [comment]
> Moved from Firefox quantum to Chrome thanks to this project ;)

For me it is because Firefox is far worse on the privacy side. If you `tcpdump` it - not only it connects to Google (for unsafe browsing and who knows what else) but also to other hosts of Amazon, Akamai, Mozilla (for telemetry and what not), OCSP etc. Chromium at least communicates only with 1 entity. Of course through certain combinations of `about:config` settings Firefox background chatter can be reduced but it requires quite a lot of fine tuning and constant monitoring as in new versions they keep adding more and more "features". When I reported all that to Mozilla they ignored and closed my bug reports, didn't update their documentation about how to stop background communication and as a whole behave in a very repulsive way. People who trust "non-profit" Mozilla (actually a multimillion dollar corporation) are very mislead imo.

**Comment by Kherby** [comment]
I love it as well!! <3
I'm using ungoogled chromium for all my GUI based network devices and never had any problem with it...
For normal browsing i still use a customized Firefox ESR 52, with noscript, uBlock Origin and a few more addons.
Firefox only sucks with youtube 4k content... On my i5 7200u Notebook youtube 4k content is causing ~65% CPU load where Chrome only needs ~12% CPU and ~15% iGPU load for the same 4k content!

**Comment by intika** [comment]
@anchev 
Most of the revenue of Mozilla is coming from google 
[Mozilla 2016](https://www.computerworld.com/article/3240008/web-browsers/mozillas-record-2016-revenue-funded-its-firefox-quantum-browser.html)
[How Mozilla Make Moeny](https://www.quora.com/How-does-the-Mozilla-Corporation-make-money) 
All that money make firefox switching to webkit questionable... they have indeed good reasons but when you see project like palemoon where just 2 developers made an amazing work... for sure there is something going on but what ? we will never know... 

@Eloston Personally am using :
50% : Palemoon as main browser, (can not live without xul)
40% : Ungoogled Chromium as secondary (mainly for its speed, and because of U.G. features)
10% : Mixed Browser Depending Used Service 
 - Chrome (for netflix)
 - Firefox v52.9.0 Mageia Custom Build (Used rarely just there to remember this old beast, but still its a custom build with many features... but as it is going nowhere in a near future i kind switched before the storm)  
 - Seamonkey (Nice little alternative when i don't want to miss with my browsing sessions) 
 - Cyberfox (Secondary alternative)
 - Waterfox (Running insecure addons)

I remember not so long ago being stuck on firefox v3/v4 for my addons my custom setup & custom build... damn those versions of firefox sky-rocked at their time

May be i am crazy using all those stuff lol... and i did even not talked about android lol

Also for the record **Windows 10** made me switch to linux fully, i really did love a lot that system... it took me many months to makes windows custom at every release with all the modifications & hack etc... but with v10 things became raging and most of the time way too much time consuming to setup, and when you do set it up windows give you a "hi 5" by and update that erase everything and you have to start from scratch... at least when you customize linux it's there for a long time if not for good. 

I always have been postponing fully switching to linux... but now that i did and with my custom build from custom Bios to custom Kernel to custom Linux LSM to custom custom KDE... it's like heaven lool now days linux evolution have reached truly amazing stage. if MS was not alone doing things like they did with Win 10 would of made them loose a lot of customers

But thanks god snowden revelation made open-sources world evolve like never before (even if we knew about it... but now politics know). and European union is not inactive in the domain.

**Comment by Eloston** [comment]
@intika 

> May be i am crazy using all those stuff lol... and i did even not talked about android lol

Lots of people like to play with their systems, whether it be a desktop, server, DIY electrical device, car modding, etc. You're definitely not alone.

> i was a little skeptical when i first find it because of the lack of website and the given name to the project

Interesting. I tend to go to GitHub (or similar services) to see what a project is like, because it allows me to see attributes that aren't visible on a website; e.g. development activity, code quality, stability, the kind of atmosphere it promotes, etc.

But that's just my opinion. Others prefer websites for a variety of reasons, and that's understandable. (If you would be interested in helping to make the website, we should discuss more in #335.)

**Comment by intika** [comment]
> Interesting. I tend to go to GitHub (or similar services) to see what a project is like, because it allows me to see attributes that aren't visible on a website; e.g. development activity, code quality, stability, the kind of atmosphere it promotes, etc.

Yeah me too but for a project like a browser (even if it's a fork) i expected to see more than a git, i know now the background but back then i was like "this is someone who are playing with chromium this is not serious and may be it will not survive a long time" but as i already said after digging in it's a whole other story... as we say "first impression is a bitch" lol

**Comment by ericdmoore** [comment]
+1 for this product. Gave you a shout out here too: https://news.ycombinator.com/item?id=18047418

**Comment by niftylettuce** [comment]
@Eloston you should set up a donation link with PayPal, Patreon, or Open Collective so you can work on this more 👍

**Comment by anchev** [comment]
"respecting our users is at the core of what we do" is the latest Google's nonsense in [this bug report about Chromes privacy issues related to connections to Google](https://bugs.chromium.org/p/chromium/issues/detail?id=795526#c23):

So once again: huge thanks to @Eloston for this great project.

**Comment by intika** [comment]
> "respecting our users is at the core of what we do" is the latest Google's nonsense in [this bug report about Chromes privacy issues related to connections to Google](https://bugs.chromium.org/p/chromium/issues/detail?id=795526#c23):
> 
> So once again: huge thanks to @Eloston for this great project.

Yes they do because if not no one would use the product, in the other hand we sometime forget that all of this is free... in the butom line we are the product... there is reason why google services are so good it's because they know so well theirs users lol hahaha

**Comment by Eloston** [comment]
@niftylettuce This is a month late, but ungoogled-chromium is a side project for me, and I intend to keep it that way for the forseeable future. Nevertheless, thank you for your show of appreciation!

**Comment by intika** [comment]
@Eloston must earn over a 6 figure a year :p so he is too generous

**Comment by Utone** [comment]
I'm very happy I found this again!  https://github.com/UnnoTed/Ungoogled-Chromium-Extension-Installer

Could this be added to: https://ungoogled-software.github.io/ungoogled-chromium-wiki/user-resources/Useful Extensions. I find it very handy to still be able to install extensions.

Thanks UnnoTed and of course @Eloston for making and this panacea of a browser! Hope you find some time 'from time  to time' to maintain these great builds!
Thank you!

> I wrote a extension to make it easier to install extensions from the webstore by following the url method stated in the [faq](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#can-i-install-extensions-from-the-chrome-webstore), All that it does is get chrome's version and extension's id and insert it into the crx url, The #extension-mime-request-handling flag is still required.
> https://github.com/UnnoTed/Ungoogled-Chromium-Extension-Installer

**Comment by CardealRusso** [comment]
Unfortunately I lost this love.

**Comment by jstkdng** [comment]
lmao
